[package]
name = "tgbin"
version = "0.1.0"
edition = "2021"

[dependencies]
pretty_env_logger = "0.5"
teloxide = "0.17.0"
log = "0.4.28"
tokio = { version = "1.47.1", features = ["full"] }
redb = "3.1.0"
